#!/usr/bin/env bash
# PreToolUse hook: Block edits to sensitive files (.env, lock files, secrets)
#
# Receives tool input as JSON on stdin. Checks CLAUDE_FILE_PATHS for
# files that should never be modified by Claude.

set -euo pipefail

# Only check file-modifying tools
case "${CLAUDE_TOOL_NAME:-}" in
    Edit|Write|NotebookEdit) ;;
    *) exit 0 ;;
esac

# Check each file path
for filepath in ${CLAUDE_FILE_PATHS:-}; do
    basename=$(basename "$filepath")
    case "$basename" in
        .env|.env.*|*.env)
            echo "BLOCKED: Refusing to edit $basename — environment files contain secrets and must be edited manually."
            exit 2
            ;;
        package-lock.json|yarn.lock|pnpm-lock.yaml)
            echo "BLOCKED: Refusing to edit $basename — lock files are managed by package managers."
            exit 2
            ;;
        *.key|*.pem|*.crt|*.cer)
            echo "BLOCKED: Refusing to edit $basename — certificate/key files must be managed manually."
            exit 2
            ;;
        output.css)
            echo "BLOCKED: output.css is generated by Tailwind — edit input.css instead."
            exit 2
            ;;
    esac
done

exit 0
